name: C# SonarQube CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Build
        run: dotnet build "excepciones - cSharp/excepciones - cSharp.sln" --configuration Release

      - name: Run tests
        run: dotnet test "excepciones - cSharp/excepciones - cSharp.sln"

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$env:PATH"

      - name: Run SonarQube Analysis
        run: |
          dotnet sonarscanner begin /k:"PRACTICA-TRY-CATCH" /d:sonar.login="d2f80d1202bc9d646fe554c02f0fc5116a954738" /o:"MARCOS_MARTINEZ_VALDEZ"
          dotnet build "excepciones - cSharp/excepciones - cSharp.sln"
          dotnet sonarscanner end /d:sonar.login="d2f80d1202bc9d646fe554c02f0fc5116a954738"
